name: StatisticsRewards
version: ${project.version}
main: me.nickax.statisticsrewards.StatisticsRewards
api-version: 1.13
author: Nickax
softdepend: [PlaceholderAPI]

commands:
  statisticsrewards:
    description: show the command list.
    aliases: [sr]
