name: StatisticsRewards
version: ${project.version}
main: me.nickax.statisticsrewards.StatisticsRewards
api-version: 1.13
softdepend: [ PlaceholderAPI ]
author: Nickax

commands:
  statisticsrewards:
    description: shows the command list.
